"""Export the PostgreSQL schema.

Two modes:

    # Offline: render straight from the SQLAlchemy metadata (no DB needed).
    python scripts/export_schema.py

    # Live: introspect the real database after `alembic upgrade head`.
    python scripts/export_schema.py --live

Both write ``docs/schema.sql``. Offline output is derived from the models, so
it records what the code expects; live output is the authoritative record of
what the database actually contains.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path
from typing import Any, Optional

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from sqlalchemy import MetaData, Table, create_mock_engine, make_url  # noqa: E402
from sqlalchemy.engine import Dialect  # noqa: E402
from sqlalchemy.schema import CreateTable, DDLElement  # noqa: E402

from app.core.config import settings  # noqa: E402
from app.db.base import Base  # noqa: E402

# Importing the package registers every model on Base.metadata.
import app.db.models  # noqa: E402,F401

OUTPUT = ROOT / "docs" / "schema.sql"

HEADER = """\
-- Fan Hub Plus - PostgreSQL schema
-- Source: {source}
-- Generated by scripts/export_schema.py - do not edit by hand.
--
-- {tables} tables, {indexes} indexes.
"""


def _compile(ddl: Any, dialect: Dialect) -> str:
    """Render a DDL construct (or a raw string) to a clean statement."""
    text = ddl.compile(dialect=dialect) if isinstance(ddl, DDLElement) else ddl
    return str(text).strip().rstrip(";") + ";"


# ------------------------------------------------------------------ offline
def _render_offline() -> tuple[str, int, int]:
    statements: list[str] = []
    holder: dict[str, Any] = {}

    def collect(sql: Any, *args: Any, **kwargs: Any) -> None:
        statements.append(_compile(sql, holder["engine"].dialect))

    engine = create_mock_engine("postgresql+asyncpg://", collect)
    holder["engine"] = engine
    Base.metadata.create_all(engine, checkfirst=False)

    n_tables = len(Base.metadata.tables)
    n_indexes = sum(len(t.indexes) for t in Base.metadata.tables.values())
    return "\n\n".join(statements), n_tables, n_indexes


# --------------------------------------------------------------------- live
def _table_ddl(inspector: Any, name: str) -> str:
    metadata = MetaData()
    table = Table(name, metadata, autoload_with=inspector)
    dialect = inspector.bind.dialect
    chunks = [_compile(CreateTable(table), dialect)]

    for index in inspector.get_indexes(name):
        cols = ", ".join(f'"{c}"' for c in index["column_names"])
        unique = "UNIQUE " if index.get("unique") else ""
        pg_opts = (index.get("dialect_options") or {}).get("postgresql") or {}
        using = f' USING {pg_opts["using"]}' if pg_opts.get("using") else ""
        chunks.append(f'CREATE {unique}INDEX "{index["name"]}" ON "{name}" ({cols}){using};')

    for fk in inspector.get_foreign_keys(name):
        ref = f'"{fk["referred_table"]}"'
        if fk.get("referred_schema"):
            ref = f'"{fk["referred_schema"]}".{ref}'
        cols = ", ".join(f'"{c}"' for c in fk["constrained_columns"])
        refcols = ", ".join(f'"{r}"' for r in fk["referred_columns"])
        ondelete = (fk.get("options") or {}).get("ondelete")
        clause = f" ON DELETE {ondelete}" if ondelete else ""
        chunks.append(
            f'ALTER TABLE "{name}" ADD FOREIGN KEY ({cols}) REFERENCES {ref} ({refcols}){clause};'
        )

    for ck in inspector.get_check_constraints(name):
        chunks.append(f'ALTER TABLE "{name}" ADD CONSTRAINT "{ck["name"]}" CHECK ({ck["sqltext"]});')

    for uq in inspector.get_unique_constraints(name):
        cols = ", ".join(f'"{c}"' for c in uq["column_names"])
        chunks.append(f'ALTER TABLE "{name}" ADD CONSTRAINT "{uq["name"]}" UNIQUE ({cols});')

    return "\n".join(chunks)


async def _render_live(database_url: str) -> tuple[str, int, int]:
    from sqlalchemy import inspect as sa_inspect
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(database_url, poolclass=None)

    def _collect_sync(conn: Any) -> tuple[str, int, int]:
        inspector = sa_inspect(conn)
        names = sorted(inspector.get_table_names())
        chunks = [_table_ddl(inspector, name) for name in names]
        return "\n\n".join(chunks), len(names), sum(
            len(inspector.get_indexes(n)) for n in names
        )

    try:
        async with engine.connect() as conn:
            return await conn.run_sync(_collect_sync)
    finally:
        await engine.dispose()


# --------------------------------------------------------------------- main
def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--live",
        action="store_true",
        help="introspect the real database instead of rendering from metadata",
    )
    parser.add_argument("--out", type=Path, default=OUTPUT, help="output .sql path")
    args = parser.parse_args(argv)

    if args.live:
        url = make_url(settings.database_url).set(drivername="postgresql+asyncpg")
        body, n_tables, n_indexes = asyncio.run(
            _render_live(url.render_as_string(hide_password=False))
        )
        source = f"live introspection of {url.get_backend_name()}"
    else:
        body, n_tables, n_indexes = _render_offline()
        source = "rendered from SQLAlchemy metadata (offline)"

    header = HEADER.format(source=source, tables=n_tables, indexes=n_indexes)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(f"{header}\n{body}\n", encoding="utf-8")
    print(f"wrote {args.out} ({n_tables} tables, {n_indexes} indexes, {source})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
