-- Fan Hub Plus - PostgreSQL schema
-- Source: rendered from SQLAlchemy metadata (offline)
-- Generated by scripts/export_schema.py - do not edit by hand.
--
-- 17 tables, 35 indexes.

CREATE TYPE bookmark_target AS ENUM ('content', 'character', 'merchandise');

CREATE TYPE message_role AS ENUM ('user', 'bot');

CREATE TYPE content_type AS ENUM ('article', 'video', 'audio', 'image');

CREATE TYPE content_status AS ENUM ('draft', 'published');

CREATE TYPE feedback_type AS ENUM ('bug', 'suggestion', 'query');

CREATE TYPE feedback_status AS ENUM ('open', 'reviewed', 'closed');

CREATE TYPE rating_scale AS ENUM ('stars', 'thumbs');

CREATE TYPE submission_status AS ENUM ('pending', 'approved', 'rejected');

CREATE TYPE user_role AS ENUM ('visitor', 'registered', 'admin');

CREATE TYPE auth_token_purpose AS ENUM ('email_verify', 'password_reset');

CREATE TABLE categories (
	id SERIAL NOT NULL, 
	name VARCHAR(60) NOT NULL, 
	slug VARCHAR(60) NOT NULL, 
	description TEXT, 
	icon_url VARCHAR(512), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_categories_slug ON categories (slug);

CREATE TABLE tags (
	id SERIAL NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	usage_count INTEGER DEFAULT '0' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_tags PRIMARY KEY (id), 
	CONSTRAINT uq_tags_name UNIQUE (name)
);

CREATE INDEX ix_tags_name_lower ON tags (lower(name));

CREATE TABLE users (
	id SERIAL NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	email VARCHAR(320) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	avatar_url VARCHAR(512), 
	role user_role DEFAULT 'registered' NOT NULL, 
	is_email_verified BOOLEAN DEFAULT 'false' NOT NULL, 
	last_login_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE INDEX ix_users_role_created_at ON users (role, created_at);

CREATE INDEX ix_users_is_email_verified ON users (is_email_verified);

CREATE TABLE bookmarks (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	content_type bookmark_target NOT NULL, 
	content_id INTEGER NOT NULL, 
	note TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	CONSTRAINT pk_bookmarks PRIMARY KEY (id), 
	CONSTRAINT uq_bookmarks_user_type_content UNIQUE (user_id, content_type, content_id), 
	CONSTRAINT fk_bookmarks_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_bookmarks_user_id_created_at ON bookmarks (user_id, created_at);

CREATE INDEX ix_bookmarks_content_type_content_id ON bookmarks (content_type, content_id);

CREATE TABLE characters (
	id SERIAL NOT NULL, 
	category_id INTEGER NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	bio TEXT, 
	image_url VARCHAR(512), 
	view_count INTEGER DEFAULT '0' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_characters PRIMARY KEY (id), 
	CONSTRAINT fk_characters_category_id_categories FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE RESTRICT
);

CREATE INDEX ix_characters_category_id ON characters (category_id);

CREATE INDEX ix_characters_name ON characters (name);

CREATE TABLE chatbot_sessions (
	id SERIAL NOT NULL, 
	user_id INTEGER, 
	session_token VARCHAR(64) NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	last_active_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_chatbot_sessions PRIMARY KEY (id), 
	CONSTRAINT fk_chatbot_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_chatbot_sessions_user_id ON chatbot_sessions (user_id);

CREATE INDEX ix_chatbot_sessions_user_id_started_at ON chatbot_sessions (user_id, started_at);

CREATE UNIQUE INDEX ix_chatbot_sessions_session_token ON chatbot_sessions (session_token);

CREATE TABLE chatbot_faqs (
	id SERIAL NOT NULL, 
	question VARCHAR(300) NOT NULL, 
	answer TEXT NOT NULL, 
	keywords JSONB DEFAULT '[]' NOT NULL, 
	category_id INTEGER, 
	priority INTEGER DEFAULT '0' NOT NULL, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	match_count INTEGER DEFAULT '0' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_chatbot_faqs PRIMARY KEY (id), 
	CONSTRAINT fk_chatbot_faqs_category_id_categories FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE SET NULL
);

CREATE INDEX ix_chatbot_faqs_is_active_priority ON chatbot_faqs (is_active, priority);

CREATE TABLE content (
	id SERIAL NOT NULL, 
	category_id INTEGER NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	type content_type NOT NULL, 
	description TEXT, 
	body_rich_text TEXT, 
	media_url VARCHAR(512), 
	release_date DATE, 
	popularity_score FLOAT DEFAULT '0' NOT NULL, 
	view_count INTEGER DEFAULT '0' NOT NULL, 
	status content_status DEFAULT 'published' NOT NULL, 
	created_by INTEGER, 
	search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, ''))) STORED, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_content PRIMARY KEY (id), 
	CONSTRAINT ck_content_view_count_non_negative CHECK (view_count >= 0), 
	CONSTRAINT fk_content_category_id_categories FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_content_created_by_users FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_content_status_release_date ON content (status, release_date);

CREATE INDEX ix_content_search_vector ON content USING gin (search_vector);

CREATE INDEX ix_content_category_id_status ON content (category_id, status);

CREATE INDEX ix_content_popularity_score ON content (popularity_score);

CREATE INDEX ix_content_type ON content (type);

CREATE TABLE events (
	id SERIAL NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	city VARCHAR(120) NOT NULL, 
	lat FLOAT NOT NULL, 
	lng FLOAT NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE, 
	ticket_url VARCHAR(512), 
	category_id INTEGER, 
	description VARCHAR(1000), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_events PRIMARY KEY (id), 
	CONSTRAINT fk_events_category_id_categories FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE SET NULL
);

CREATE INDEX ix_events_city ON events (city);

CREATE INDEX ix_events_start_date ON events (start_date);

CREATE INDEX ix_events_lat_lng ON events (lat, lng);

CREATE TABLE feedback (
	id SERIAL NOT NULL, 
	user_id INTEGER, 
	type feedback_type NOT NULL, 
	message TEXT NOT NULL, 
	status feedback_status DEFAULT 'open' NOT NULL, 
	admin_note TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_feedback PRIMARY KEY (id), 
	CONSTRAINT fk_feedback_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_feedback_type ON feedback (type);

CREATE INDEX ix_feedback_user_id ON feedback (user_id);

CREATE INDEX ix_feedback_status_created_at ON feedback (status, created_at);

CREATE TABLE merchandise (
	id SERIAL NOT NULL, 
	category_id INTEGER NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	description VARCHAR(500), 
	image_url VARCHAR(512), 
	tag VARCHAR(60), 
	is_upcoming BOOLEAN DEFAULT 'false' NOT NULL, 
	release_date VARCHAR(40), 
	view_count INTEGER DEFAULT '0' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_merchandise PRIMARY KEY (id), 
	CONSTRAINT fk_merchandise_category_id_categories FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE RESTRICT
);

CREATE INDEX ix_merchandise_tag ON merchandise (tag);

CREATE INDEX ix_merchandise_category_id_is_upcoming ON merchandise (category_id, is_upcoming);

CREATE INDEX ix_merchandise_category_id ON merchandise (category_id);

CREATE TABLE fan_submissions (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	body TEXT NOT NULL, 
	category_id INTEGER, 
	status submission_status DEFAULT 'pending' NOT NULL, 
	review_note TEXT, 
	reviewed_by INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_fan_submissions PRIMARY KEY (id), 
	CONSTRAINT fk_fan_submissions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_fan_submissions_category_id_categories FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE SET NULL, 
	CONSTRAINT fk_fan_submissions_reviewed_by_users FOREIGN KEY(reviewed_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_fan_submissions_user_id ON fan_submissions (user_id);

CREATE INDEX ix_fan_submissions_status_created_at ON fan_submissions (status, created_at);

CREATE TABLE user_preferences (
	user_id INTEGER NOT NULL, 
	favorite_categories JSONB DEFAULT '[]' NOT NULL, 
	display_prefs JSONB DEFAULT '{}' NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_user_preferences PRIMARY KEY (user_id), 
	CONSTRAINT fk_user_preferences_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE auth_tokens (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	purpose auth_token_purpose NOT NULL, 
	token_hash VARCHAR(64) NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	used_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	CONSTRAINT pk_auth_tokens PRIMARY KEY (id), 
	CONSTRAINT fk_auth_tokens_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT uq_auth_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_auth_tokens_expires_at ON auth_tokens (expires_at);

CREATE INDEX ix_auth_tokens_user_purpose ON auth_tokens (user_id, purpose);

CREATE TABLE chatbot_messages (
	id SERIAL NOT NULL, 
	session_id INTEGER NOT NULL, 
	role message_role NOT NULL, 
	message TEXT NOT NULL, 
	matched_faq_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_chatbot_messages PRIMARY KEY (id), 
	CONSTRAINT fk_chatbot_messages_session_id_chatbot_sessions FOREIGN KEY(session_id) REFERENCES chatbot_sessions (id) ON DELETE CASCADE, 
	CONSTRAINT fk_chatbot_messages_matched_faq_id_chatbot_faqs FOREIGN KEY(matched_faq_id) REFERENCES chatbot_faqs (id) ON DELETE SET NULL
);

CREATE INDEX ix_chatbot_messages_session_id_created_at ON chatbot_messages (session_id, created_at);

CREATE TABLE content_tags (
	content_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL, 
	CONSTRAINT pk_content_tags PRIMARY KEY (content_id, tag_id), 
	CONSTRAINT fk_content_tags_content_id_content FOREIGN KEY(content_id) REFERENCES content (id) ON DELETE CASCADE, 
	CONSTRAINT fk_content_tags_tag_id_tags FOREIGN KEY(tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

CREATE INDEX ix_content_tags_tag_id ON content_tags (tag_id);

CREATE TABLE ratings (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	content_id INTEGER NOT NULL, 
	scale rating_scale DEFAULT 'stars' NOT NULL, 
	value INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_ratings PRIMARY KEY (id), 
	CONSTRAINT uq_ratings_user_content UNIQUE (user_id, content_id), 
	CONSTRAINT ck_ratings_rating_value_matches_scale CHECK ((scale = 'stars' AND value BETWEEN 1 AND 5) OR (scale = 'thumbs' AND value IN (-1, 1))), 
	CONSTRAINT fk_ratings_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_ratings_content_id_content FOREIGN KEY(content_id) REFERENCES content (id) ON DELETE CASCADE
);

CREATE INDEX ix_ratings_content_id ON ratings (content_id);

CREATE INDEX ix_ratings_user_id ON ratings (user_id);
